---
- hosts: all
  become: true

  tasks:
    - name: Create user on linux
      gather_facts: false
      vars:
        - user: "{{ morpheus['customOptions']['username'] }}"
        - password: "{{ lookup('cypher','secret=ansible/gustavo') }}"
    - name: Create a login user
      user:
        name: "{{ user }}"
        password: "{{ password }}"
        groups:
          - wheel
        state: present
