- name: Create user on a linux server
  hosts: all
  become: yes
  gather_facts: false
  vars:
    - user: "{{ morpheus['customOptions']['username'] }}"
    - password: "{{ lookup('cypher','secret=ansible/gustavo') }}"
  tasks:
    - name: Create a login user
      user:
        name: "{{ user }}"
        password: "{{ password }}"
        groups:
          - wheel
        state: present
