--- 
- name: "Install all critical and security updates"
  register: update_result
  win_updates: 
    category_names: 
      - CriticalUpdates
      - SecurityUpdates
    state: installed
- name: "Reboot host if required"
  when: update_result.reboot_required
  win_reboot: ~
