- name: Test cypher/input
  hosts: all
  become: yes
  gather_facts: false
  vars:
    - user: "{{ morpheus['customOptions']['username'] }}"
    - password: "{{ lookup('cypher','secret=secret/ansible') }}"
  tasks:
    - name: Exibir mensagem
      debug:
        msg: "User: '{{ user }}' password: '{{ password }}'"
