--- 
- 
  hosts: all
  name: "Download and unzip file using cypher"
  tasks: 
    - become: true
      get_url: 
        dest: /etc/
        url: "https://1drv.ms/u/s!An2vGV4ZzOlOgl2bb5jFFapqwcFS?e=wyXeCp"
      name: "download archive"
    - extra_opts: 
        - "-P"
        - "{{ lookup('cypher','secret=secret/ansible') }}"
      name: "unzip encrypted zip"
      unarchive: 
        dest: /etc/teste
        src: teste.zip
