---
- name: Download and unzip file using cypher
  hosts: all
  tasks:
    - name: download archive
      become: yes
      get_url:
        url: https://1drv.ms/u/s!An2vGV4ZzOlOgl2bb5jFFapqwcFS?e=wyXeCp
        dest: /etc/
    - name: unzip encrypted zip
      unarchive:
        src: teste.zip
        dest: /etc/teste
      extra_opts:
        - "-P"
        - "{{ lookup('cypher','secret=secret/ansible') }}"
